language: java
dist: trusty
install: true
script: mvn -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn clean install
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
notifications:
  email: false
